version: '3.7'
services:

  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    container_name: plexms
    ports:
      - 32400:32400
      - 3005:3005
      - 8324:8324
      - 32469:32469
      - 1900:1900
      - 32410:32410
      - 32412:32412
      - 32413:32413
      - 32414:32414

    environment:
      - PUID= 1000
      - PGID= 1000
      - TZ=America/Mexico_City
      - PLEX_CLAIM=claim-P1HfTuXPu5F--AADx5k8
      - HOSTNAME=”PlexServer”

    volumes:
      - plexms:/config
      - plexms:/transcode
      - plexms:/media
volumes:
  plexms:  
