version: '3.7'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.vinz'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.vinz/'
    ports:
      - '8085:80'
      - '8443:443'
    expose:
      - '8085'
      - '8443'
    volumes:
      - '/home/vinz/Descargas/gitlab/config:/etc/gitlab'
      - '/home/vinz/Descargas/gitlab/logs:/var/log/gitlab'
      - '/home/vinz/Descargas/gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
   #restart: always
    depends_on:
      - web
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/home/vinz/Descargas/gitlab/gitlab-runner:/etc/gitlab-runner'
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network
