version: "3"
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8086:8081"
    expose:
      - "8086"
    volumes:
      - /home/vinz/Vídeos:/downloads
